#include "vss.h"

CALL(TEXT_SIZE, TS)

CALL(BG_COLOR, CS)
CALL(COLOR, CS)
CALL(BO_COLOR, CS)

CALL(SIZE, SS)
CALL(PADDING, SS)
CALL(TABLE_PADDING, s, )
CALL(CENTER_ABS_V, l, )
CALL(ABS_PADDING, s, xl, )
MARGIN(l)

CALL(HORIZONTAL, SS)
CALL(VERTICAL, SS)
CALL(FLEX_VERTICAL, SS)

CALL(ROUND_EDGE, l, xl)
CALL(ROUND_TEXT, , xl)
/* CALL2(ROUND_PADDING, , , l, xXl, Xxl, ) */
ROUND_PADDING( , xXl)
ROUND_PADDING( , Xxl)
ROUND_PADDING( l, )

CALL(FIXED, s, xs, l, )

main > .abs.J { bottom: S_; }
